### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by CodexBookshelf** [CodexBookshelf/crocotile3dtogodot#1]
1. Base Godot Project (from legacy)
- [ ] basic 1st person mechanics with 2D characters in a 3D environment.
- [ ] basic AI for NPCs.
- [x] basic collisions.
- [x] basic 3D camera.

2. FPS (project 1)
- [ ] 1st person interactions with 2D characters and 3D environment.
- [ ] Agressive AI for NPCs.
- [ ] Character game states.
- [ ] NPCs game states.
